@echo off
echo ========================================
echo API Key Configuration
echo ========================================
echo.

set CONFIG_FILE=demo\src\main\resources\application-local.properties

REM Check if config file exists
if exist "%CONFIG_FILE%" (
    echo Configuration file found: %CONFIG_FILE%
    echo.
    
    REM Check if API key is already set
    findstr /C:"nvidia.api.key=nvapi-" "%CONFIG_FILE%" >nul 2>&1
    if %errorlevel% equ 0 (
        echo [INFO] API key appears to be already configured.
        echo.
        set /p RECONFIGURE="Do you want to reconfigure it? (y/n): "
        if /i not "%RECONFIGURE%"=="y" (
            echo Configuration skipped.
            echo.
            pause
            exit /b 0
        )
    )
) else (
    echo Creating new configuration file...
    echo.
)

echo.
echo ========================================
echo Get your NVIDIA API Key:
echo ========================================
echo 1. Visit: https://build.nvidia.com/
echo 2. Sign in or create an account
echo 3. Navigate to any model (e.g., Nemotron)
echo 4. Click "Get API Key"
echo 5. Copy your API key (starts with "nvapi-")
echo ========================================
echo.

set /p API_KEY="Enter your NVIDIA API key: "

if "%API_KEY%"=="" (
    echo.
    echo [ERROR] No API key provided!
    echo Configuration cancelled.
    pause
    exit /b 1
)

echo.
echo Writing configuration...

REM Create the config file
(
echo # Local Development Configuration
echo # Generated by 2_CONFIGURE_API_KEY.bat
echo.
echo # NVIDIA NIM API Configuration
echo nvidia.api.key=%API_KEY%
echo nvidia.api.base-url=https://integrate.api.nvidia.com/v1
echo nvidia.embedding.model=nvidia/llama-3.2-nemoretriever-300m-embed-v1
echo nvidia.chat.model=nvidia/nemotron-3-super-120b-a12b
echo.
echo # Spring AI OpenAI Configuration ^(uses NVIDIA NIM^)
echo spring.ai.openai.api-key=%API_KEY%
echo spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
echo spring.ai.openai.chat.options.model=nvidia/nemotron-3-super-120b-a12b
echo spring.ai.openai.chat.options.temperature=0.7
echo spring.ai.openai.chat.options.max-tokens=1024
echo.
echo # Database Configuration
echo spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
echo spring.datasource.username=raguser
echo spring.datasource.password=ragpass
echo.
echo # Application Settings
echo server.port=8080
echo spring.jpa.hibernate.ddl-auto=none
echo spring.sql.init.mode=always
echo.
echo # Logging
echo logging.level.com.example.demo=DEBUG
echo logging.level.org.springframework.ai=DEBUG
) > "%CONFIG_FILE%"

if %errorlevel% equ 0 (
    echo.
    echo ========================================
    echo [SUCCESS] Configuration saved!
    echo ========================================
    echo File: %CONFIG_FILE%
    echo.
    echo Your API key has been configured.
    echo.
    echo Next step:
    echo   Run: 3_START_APPLICATION.bat
    echo ========================================
) else (
    echo.
    echo [ERROR] Failed to write configuration file!
    echo Please check file permissions.
)

echo.
pause
