@echo off
setlocal enabledelayedexpansion

echo ========================================
echo   IMPRS - One-Click Setup
echo   Intelligent Memory Preservation System
echo ========================================
echo.

set API_KEY=%~1
set CONFIG_FILE=demo\src\main\resources\application-local.properties

echo [1/6] Checking prerequisites...
echo.
call :check_prerequisites
if !ERROR_PREREQ! equ 1 (
    echo.
    echo [FAILED] Prerequisites check failed
    pause
    exit /b 1
)
echo [OK] Prerequisites met
echo.

echo [2/6] Configuring API key...
echo.
if "%API_KEY%"=="" (
    call :prompt_api_key
) else (
    echo [INFO] Using API key from command line argument
)
if !ERROR_API! equ 1 (
    echo [FAILED] API key configuration failed
    pause
    exit /b 1
)
echo.

echo [3/6] Starting Docker database...
echo.
call :start_database
if !ERROR_DB! equ 1 (
    echo [FAILED] Database startup failed
    pause
    exit /b 1
)
echo.

echo [4/6] Building application...
echo.
call :build_app
if !ERROR_BUILD! equ 1 (
    echo [FAILED] Build failed
    pause
    exit /b 1
)
echo.

echo [5/6] Starting application...
echo.
call :start_app
if !ERROR_START! equ 1 (
    echo [FAILED] Application start failed
    pause
    exit /b 1
)
echo.

echo [6/6] Opening Swagger UI...
echo.
start http://localhost:8080/swagger-ui/index.html

echo.
echo ========================================
echo   [SUCCESS] IMPRS is ready!
echo ========================================
echo.
echo   Access: http://localhost:8080/swagger-ui/index.html
echo.
echo   Press Ctrl+C to stop the application
echo ========================================
echo.

rem Don't pause - let the app run
cd demo
call mvnw.cmd spring-boot:run -Dspring-boot.run.profiles=local
pause
exit /b 0

rem ============================================================
rem  Helper: detect docker compose command (v2 vs v1)
rem ============================================================
:detect_compose
set COMPOSE_CMD=
docker compose version >nul 2>&1
if %errorlevel% equ 0 (
    set COMPOSE_CMD=docker compose
    goto :eof
)
docker-compose --version >nul 2>&1
if %errorlevel% equ 0 (
    set COMPOSE_CMD=docker-compose
    goto :eof
)
echo [ERROR] Neither "docker compose" nor "docker-compose" found
goto :eof

rem ============================================================
:check_prerequisites
set ERROR_PREREQ=0

docker --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not installed
    set ERROR_PREREQ=1
    goto :prompt_install_docker
)

docker ps >nul 2>&1
if errorlevel 1 (
    echo [WARNING] Docker daemon is not running
    call :prompt_start_docker
    if !ERROR_PREREQ! equ 1 goto :eof
)

java -version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Java is not installed or not on PATH
    set ERROR_PREREQ=1
)
goto :eof

:prompt_install_docker
echo.
set /p DOCKER_CHOICE="Download Docker Desktop? (y/n): "
if /i "!DOCKER_CHOICE!"=="y" start https://www.docker.com/products/docker-desktop
goto :eof

:prompt_start_docker
echo.
set /p DOCKER_START="Start Docker Desktop now? (y/n): "
if /i "!DOCKER_START!"=="y" (
    echo [INFO] Launching Docker Desktop...
    start "" "C:\Program Files\Docker\Docker\Docker Desktop.exe"
    echo [INFO] Waiting up to 60s for Docker to become ready...
    set /a WAIT_COUNT=0
    :wait_docker_loop
    timeout /t 5 /nobreak >nul
    set /a WAIT_COUNT+=5
    docker ps >nul 2>&1
    if %errorlevel% equ 0 (
        echo [OK] Docker is ready
        set ERROR_PREREQ=0
        goto :eof
    )
    if !WAIT_COUNT! lss 60 goto :wait_docker_loop
    echo [ERROR] Docker did not start within 60 seconds
    set ERROR_PREREQ=1
) else (
    set ERROR_PREREQ=1
)
goto :eof

:prompt_api_key
echo ========================================
echo Get your NVIDIA API Key:
echo ========================================
echo 1. Visit: https://build.nvidia.com/
echo 2. Sign in or create account
echo 3. Get API key from any model
echo ========================================
echo.
set /p API_KEY="Enter NVIDIA API key (or press Enter to configure later): "
if "%API_KEY%"=="" (
    echo [WARNING] No API key entered - configuration skipped
    echo You can configure later by editing:
    echo   %CONFIG_FILE%
    set ERROR_API=0
    goto :eof
)
goto :write_api_config

:write_api_config
(
echo # Local Development Configuration
echo # Generated by SETUP.bat
echo.
echo # NVIDIA NIM API Configuration
echo nvidia.api.key=%API_KEY%
echo nvidia.api.base-url=https://integrate.api.nvidia.com/v1
echo nvidia.embedding.model=nvidia/llama-3.2-nemoretriever-300m-embed-v1
echo nvidia.chat.model=nvidia/nemotron-3-super-120b-a12b
echo.
echo # Spring AI OpenAI Configuration ^(uses NVIDIA NIM^)
echo spring.ai.openai.api-key=%API_KEY%
echo spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
echo spring.ai.openai.chat.options.model=nvidia/nemotron-3-super-120b-a12b
echo spring.ai.openai.chat.options.temperature=0.7
echo spring.ai.openai.chat.options.max-tokens=1024
echo.
echo # Database Configuration
echo spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
echo spring.datasource.username=raguser
echo spring.datasource.password=ragpass
echo.
echo # Application Settings
echo server.port=8080
echo spring.jpa.hibernate.ddl-auto=none
echo spring.sql.init.mode=always
echo.
echo # Logging
echo logging.level.com.example.demo=DEBUG
echo logging.level.org.springframework.ai=DEBUG
) > "%CONFIG_FILE%"
set ERROR_API=0
echo [OK] API key configured
goto :eof

:start_database
set ERROR_DB=0

call :detect_compose
if "!COMPOSE_CMD!"=="" (
    set ERROR_DB=1
    goto :eof
)

rem Check if container already exists (inspect is reliable regardless of format)
docker inspect rag-postgres >nul 2>&1
if %errorlevel% equ 0 (
    echo [INFO] Container rag-postgres already exists
    rem Check running state via inspect
    for /f "delims=" %%S in ('docker inspect --format "{{.State.Running}}" rag-postgres 2^>nul') do set CONTAINER_RUNNING=%%S
    if "!CONTAINER_RUNNING!"=="true" (
        echo [OK] Container is already running
    ) else (
        echo [INFO] Container is stopped - starting it...
        docker start rag-postgres
        if %errorlevel% neq 0 (
            echo [ERROR] Failed to start existing container
            set ERROR_DB=1
            goto :eof
        )
        echo [OK] Container started
    )
) else (
    echo [INFO] Creating new container via %COMPOSE_CMD%...
    %COMPOSE_CMD% up -d
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to create container
        set ERROR_DB=1
        goto :eof
    )
    echo [OK] Container created
)

echo [INFO] Waiting for database to be ready (up to 30s)...
set /a DB_WAIT=0
:wait_db_loop
timeout /t 5 /nobreak >nul
set /a DB_WAIT+=5
docker exec rag-postgres pg_isready -U raguser -d ragdb >nul 2>&1
if %errorlevel% equ 0 goto :db_ready
if !DB_WAIT! lss 30 goto :wait_db_loop
echo [WARNING] Database health check timed out - continuing anyway...
goto :check_schema

:db_ready
echo [OK] Database is ready

:check_schema
docker exec rag-postgres psql -U raguser -d ragdb -c "\dt" 2>nul | findstr "document_chunks" >nul 2>&1
if %errorlevel% neq 0 (
    echo [INFO] Initializing database schema...
    powershell -Command "Get-Content demo\src\main\resources\schema.sql | docker exec -i rag-postgres psql -U raguser -d ragdb" >nul 2>&1
    if %errorlevel% equ 0 (
        echo [OK] Schema initialized
    ) else (
        echo [ERROR] Schema initialization failed
        set ERROR_DB=1
    )
) else (
    echo [OK] Schema already exists
)
goto :eof

:build_app
set ERROR_BUILD=0

cd demo
if not exist "mvnw.cmd" (
    echo [ERROR] Maven wrapper not found in demo\
    set ERROR_BUILD=1
    cd ..
    goto :eof
)

echo [INFO] Building... (this may take 2-3 minutes on first run)
call mvnw.cmd clean package -DskipTests
if %errorlevel% neq 0 (
    echo [ERROR] Build failed
    set ERROR_BUILD=1
    cd ..
    goto :eof
)
echo [OK] Build successful
cd ..
goto :eof

:start_app
set ERROR_START=0
echo [INFO] Starting Spring Boot application...
echo [INFO] This takes ~15 seconds to initialize
echo.
goto :eof
